###
GET http://localhost:3001/sales

###
POST http://localhost:3001/sales
content-type: application/json

{
  "productName": "SmarTV",
  "infos": {
    "saleDate": "19/02/2022",
    "warrantyPeriod": 1
  }
}